### ISSUE TITLE
No module named 'radbelt.core'

### ISSUE THREAD

**Issue by spinnak3r** [nasa/radbelt#38]
Hi,

I installed the package on a new python environment (I have tried python 3.8 and 3.10), but I simply get this error when I try to run the example.

`Traceback (most recent call last):
  File "/home/lubuntu/RB/radbelt/test.py", line 1, in <module>
    from radbelt import get_flux
  File "/home/lubuntu/RB/radbelt/radbelt/__init__.py", line 15, in <module>
    from .core import igrf as _igrf, aep8 as _aep8
ModuleNotFoundError: No module named 'radbelt.core'
`
Any idea what the problem is?
Thank you

**Comment by lpsinger** [comment]
Sounds like an issue with your PYTHONPATH.

**Comment by donidona** [comment]
I have the same problem, @spinnak3r did you manage to fix it?

**Comment by spinnak3r** [comment]
@donidona No, I didn't. I even asked two lab colleagues to try to install it too but they get the same error. The package remains, at least to us, unusable. 
Installing the igrf package from pip removed the igrf import error, but aep8 is only available locally and that error remains. In my opinion there must be something missing in the `__init__.py` file.

**Comment by lpsinger** [comment]
Is this fixed in version 0.1.4?

**Comment by donidona** [comment]
I have the same problem with version 0.1.4

**Comment by donidona** [comment]
@lpsinger thanks for the quick support, however the problem still persists: 
`ImportError: DLL load failed while importing core: The specified module could not be found.`

**Comment by lpsinger** [comment]
I think that #43 will fix this once I do a release, but I have to debug some Windows build issues first.

What operating system, architecture, and Python distribution are you using? How are you installing radbelt?

**Comment by lpsinger** [comment]
> Installing the igrf package from pip removed the igrf import error

The igrf package on PyPI is not related to this package, and it is not a dependency.

**Comment by donidona** [comment]
> 

- Microsoft Windows 10 Pro Version 10.0.19045 Build 19045
- Python 3.10.6
- System Type	x64-based PC

I installed radbelt 0.1.4 using `git clone https://github.com/nasa/radbelt.git` and `pip install .` and get the error `ImportError: DLL load failed while importing core: The specified module could not be found.`

**Comment by lpsinger** [comment]
Yes, that’s the issue I’m seeing too in the GitHub Actions pipeline.

It should be fixed now on Linux and macOS. Windows will take longer because I don’t use Windows and I am not familiar wi to the Windows compiler and linker tool chain.

**Comment by lpsinger** [comment]
It looks like the Windows build has never worked. Unfortunately, I don't have sufficient expertise with Windows to debug it myself. Pull requests are welcome. See https://github.com/nasa/radbelt#known-issues and #47.

@spinnak3r, based on your initial report, it looks like you are using Linux. I just released version 0.1.5. Do you find that version 0.1.5 fixes your issue on Linux?
